### ISSUE TITLE
Detect SFDC Workspace

### ISSUE THREAD

**Issue by aranwe** [tr4uma/swift-sfdc#31]
Hi,
swift-sfdc creates .swift💫sfdc.json in all opened workspaces - I think it should detect presence of package.xml in the root before it inits itself.

Also I believe there should not be "💫" char in the config name :) 

Thank you!

**Comment by tr4uma** [comment]
Which version are you using?

**Comment by aranwe** [comment]
Name: swift-sfdc
Id: tr4uma.swift-sfdc
Description: A VSCode extension for increased productivity on salesforce.com projects.
Version: 0.0.12
Publisher: tr4uma
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=tr4uma.swift-sfdc


re 💫 - yes, I know its Unicode - however due to compatibility with some filesystems I would refrain from using it. Also from UX perspective - configs are not the most important files in the repository and with special chars tend to draw attention.

**Comment by tr4uma** [comment]
Sorry for asking again, are you sure you are running the latest version of the plugin? Did you try uninstalling and re-installing? I cannot reproduce the problem with the config file creation, even switching workspace doesn't accidentally create the config file.
