### ISSUE TITLE
Does this work with SFDX/Source Format?

### ISSUE THREAD

**Issue by MorganMarchese** [tr4uma/swift-sfdc#40]
Sorry, this isn't really an "issue" but I don't know where else to ask. I just found your plugin today and am intrigued about its potential use for creating fields/FLS and making profile changes.

However, we don't use the metadata API format for our source code, we use the SFDX source format. Is this plugin compatible? If so, it would be nice to call that out somewhere in the Description/Readme so that others know it will work with that file structure.

**Comment by tr4uma** [comment]
Hi, @MorganMarchese , unfortunately it is currently not compatible with SFDX project structure, which creates the whole project under the /force-app/main/default folder. You can find the supported file structure in the first paragraph of the readme, which is the one created by the ANT migration tool and forcecode/fast-sfdc VSCode extensions.
Support for SFDX project structure is currently not planned, but you can always configure SFDX to use the "old" project structure.
