### ISSUE TITLE
Make folder for metadata configurable

### ISSUE THREAD

**Issue by oscarsgit** [tr4uma/swift-sfdc#43]
Could you please make the folder with the metadata something that can be configured using settings. Defaulting it to /src/ root folder means that our team is currently unable to make use of this plugin as our project directory does not have that format and it would be too much to change our folder structure to be able to make use of this plugin.

Using the following Visual Studio Code:
Version: 1.55.2 (system setup)
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041

Plugin:
tr4uma.swift-sfdc
v0.0.23

**Comment by tr4uma** [comment]
Implemented in 1.0.0
