### ISSUE TITLE
Unable to access the project direcory

### ISSUE THREAD

**Issue by Tanmays9** [tr4uma/swift-sfdc#51]
The getObjectsFromMetadata method in objects and profiles is working not as expected probably due to additional slash "/" in beginning of dir structure
I have fixed it temperary by : 

-------------------------------------------------------------------------------------------------------------------------------
getObjectsFromMetaData: function (): SObjectFile[] {
    let p = path.join(ConfigManager.getInstance().getVSCodeRoot() as string, ConfigManager.getInstance().retrieveBackwardCompatibleRootFolder(), 'objects')
    **p = p.slice(1);**
    const files = fs.readdirSync(p, { withFileTypes: true })
    if (files.length === 0) { throw Error('No SObject definition file was found in folder ' + p) }
    return this.generateSObjectDefinitions(files, p)
  },
--------------------------------------------------------------------------------------------------------------------------
Also, please add a sample swift config file to read me for understanding of its customization.
But good extension Thank you

**Comment by tr4uma** [comment]
This should be fixed in today's release.
I also added a sample as requested.
